#!/usr/bin/env python3
"""
Stripe Billing Environment Setup Script
This script helps you configure the necessary environment variables for Stripe billing integration.
"""

import os
import sys

def setup_billing_env():
    print("🚀 Dify Stripe Billing Setup")
    print("=" * 50)

    # Check if .env file exists
    env_file = "api/.env"
    if not os.path.exists(env_file):
        print(f"Creating {env_file} file...")
        open(env_file, 'a').close()

    # Read existing .env file
    env_vars = {}
    if os.path.exists(env_file):
        with open(env_file, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    env_vars[key] = value

    print("\nPlease provide the following Stripe configuration:")
    print("(You can get these from your Stripe Dashboard)")
    print()

    # Collect basic Stripe configuration
    stripe_config = {
        'BILLING_ENABLED': 'true',
        'STRIPE_API_KEY': input("Enter your Stripe Secret Key (sk_test_... or sk_live_...): ").strip(),
        'STRIPE_PUBLISHABLE_KEY': input("Enter your Stripe Publishable Key (pk_test_... or pk_live_...): ").strip(),
        'STRIPE_WEBHOOK_SECRET': input("Enter your Stripe Webhook Secret (whsec_...): ").strip(),
        'NEXT_PUBLIC_APP_URL': input("Enter your app URL (default: http://localhost:3000): ").strip() or "http://localhost:3000"
    }

    # Validate basic inputs
    if not stripe_config['STRIPE_API_KEY'].startswith(('sk_test_', 'sk_live_')):
        print("❌ Error: Stripe API Key should start with 'sk_test_' or 'sk_live_'")
        return

    if not stripe_config['STRIPE_PUBLISHABLE_KEY'].startswith(('pk_test_', 'pk_live_')):
        print("❌ Error: Stripe Publishable Key should start with 'pk_test_' or 'pk_live_'")
        return

    if not stripe_config['STRIPE_WEBHOOK_SECRET'].startswith('whsec_'):
        print("❌ Error: Stripe Webhook Secret should start with 'whsec_'")
        return

    # Collect Price IDs for different plans
    print("\n📋 Now provide the Stripe Price IDs for different plans:")
    print("(You can create these in Stripe Dashboard → Products)")
    print()

    # Professional plan prices
    print("Professional Plan:")
    prof_monthly = input("  Monthly Price ID (price_...): ").strip()
    prof_yearly = input("  Yearly Price ID (price_...): ").strip()

    # Team plan prices
    print("\nTeam Plan:")
    team_monthly = input("  Monthly Price ID (price_...): ").strip()
    team_yearly = input("  Yearly Price ID (price_...): ").strip()

    # Validate price IDs
    price_ids = {
        'STRIPE_PROFESSIONAL_MONTHLY_PRICE_ID': prof_monthly,
        'STRIPE_PROFESSIONAL_YEARLY_PRICE_ID': prof_yearly,
        'STRIPE_TEAM_MONTHLY_PRICE_ID': team_monthly,
        'STRIPE_TEAM_YEARLY_PRICE_ID': team_yearly,
    }

    for key, price_id in price_ids.items():
        if price_id and not price_id.startswith('price_'):
            print(f"❌ Error: {key} should start with 'price_'")
            return

    # Add price IDs to configuration
    stripe_config.update(price_ids)

    # Update environment variables
    env_vars.update(stripe_config)

    # Write back to .env file
    with open(env_file, 'w') as f:
        f.write("# Dify Configuration\n")
        f.write("# Generated by setup_billing_env.py\n\n")

        # Write billing configuration
        f.write("# ================================\n")
        f.write("# STRIPE BILLING CONFIGURATION\n")
        f.write("# ================================\n")
        billing_keys = [
            'BILLING_ENABLED', 'STRIPE_API_KEY', 'STRIPE_PUBLISHABLE_KEY',
            'STRIPE_WEBHOOK_SECRET', 'NEXT_PUBLIC_APP_URL',
            'STRIPE_PROFESSIONAL_MONTHLY_PRICE_ID', 'STRIPE_PROFESSIONAL_YEARLY_PRICE_ID',
            'STRIPE_TEAM_MONTHLY_PRICE_ID', 'STRIPE_TEAM_YEARLY_PRICE_ID'
        ]
        for key in billing_keys:
            if key in env_vars and env_vars[key]:
                f.write(f"{key}={env_vars[key]}\n")

        f.write("\n# ================================\n")
        f.write("# OTHER CONFIGURATIONS\n")
        f.write("# ================================\n")

        # Write other configurations
        other_configs = {
            'MARKETPLACE_ENABLED': 'false',
            'PLUGIN_DAEMON_URL': 'http://localhost:5002',
            'PLUGIN_DAEMON_KEY': 'dummy_key_for_testing',
            'SECRET_KEY': 'your-secret-key-here',
            'DEPLOY_ENV': 'DEVELOPMENT',
            'DEBUG': 'true'
        }

        for key, default_value in other_configs.items():
            value = env_vars.get(key, default_value)
            f.write(f"{key}={value}\n")

    print(f"\n✅ Configuration saved to {env_file}")
    print("\n🎉 Setup complete! Next steps:")
    print("1. Restart your Dify services")
    print("2. Go to http://localhost:3000 and test the billing functionality")
    print("3. Use Stripe test card: 4242 4242 4242 4242")
    print("\nFor production deployment, replace test keys with live keys!")
    print("\n📋 Plan Structure:")
    print("- Sandbox: Free (no billing)")
    print("- Professional: Monthly/Yearly options")
    print("- Team: Monthly/Yearly options")

if __name__ == "__main__":
    try:
        setup_billing_env()
    except KeyboardInterrupt:
        print("\n\n❌ Setup cancelled by user")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Error during setup: {e}")
        sys.exit(1)
