"""Add subscription table for billing

Revision ID: a1b2c3d4e5f6
Revises: 0ab65e1cc7fa
Create Date: 2025-01-20 12:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '0ab65e1cc7fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
        sa.Column('id', UUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column('team_id', sa.String(length=255), nullable=False),
        sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
        sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
        sa.Column('stripe_price_id', sa.String(length=255), nullable=True),
        sa.Column('stripe_current_period_end', sa.DateTime(), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
        sa.PrimaryKeyConstraint('id', name='subscription_pkey'),
        sa.UniqueConstraint('team_id', name='unique_team_subscription')
    )

    # Add indexes for performance
    op.create_index('subscription_team_id_idx', 'subscriptions', ['team_id'])
    op.create_index('subscription_stripe_customer_id_idx', 'subscriptions', ['stripe_customer_id'])
    op.create_index('subscription_stripe_subscription_id_idx', 'subscriptions', ['stripe_subscription_id'])
    op.create_index('subscription_stripe_price_id_idx', 'subscriptions', ['stripe_price_id'])
    op.create_index('subscription_status_idx', 'subscriptions', ['status'])

    # Add unique constraints for stripe identifiers
    op.create_unique_constraint('unique_stripe_customer_id', 'subscriptions', ['stripe_customer_id'])
    op.create_unique_constraint('unique_stripe_subscription_id', 'subscriptions', ['stripe_subscription_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop unique constraints
    op.drop_constraint('unique_stripe_subscription_id', 'subscriptions', type_='unique')
    op.drop_constraint('unique_stripe_customer_id', 'subscriptions', type_='unique')

    # Drop indexes
    op.drop_index('subscription_status_idx', table_name='subscriptions')
    op.drop_index('subscription_stripe_price_id_idx', table_name='subscriptions')
    op.drop_index('subscription_stripe_subscription_id_idx', table_name='subscriptions')
    op.drop_index('subscription_stripe_customer_id_idx', table_name='subscriptions')
    op.drop_index('subscription_team_id_idx', table_name='subscriptions')

    # Drop table
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
